//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChurchAPM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Church
    {
        public string ChName { get; set; }
        public string Adress { get; set; }
        public int DonationsId { get; set; }
        public int EmployerId { get; set; }
        public int EventsId { get; set; }
        public int FixedAssetsId { get; set; }
        public int InventoryItemsId { get; set; }
        public int AdminsId { get; set; }
    
        public virtual Admins Admins { get; set; }
        public virtual ChEvents ChEvents { get; set; }
        public virtual Donations Donations { get; set; }
        public virtual Employers Employers { get; set; }
        public virtual FixedAssets FixedAssets { get; set; }
        public virtual InventoryItems InventoryItems { get; set; }
    }
}
