//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChurchAPM
{
    using System;
    using System.Collections.Generic;
    
    public partial class FixedAssets
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FixedAssets()
        {
            this.Church = new HashSet<Church>();
        }
    
        public int ID { get; set; }
        public System.DateTime DateOfEntry { get; set; }
        public System.DateTime ExpirationDate { get; set; }
        public int AnnualDepreciationRate { get; set; }
        public int InitialCost { get; set; }
        public string GroupName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Church> Church { get; set; }
    }
}
